version: '3'

services:
  # Express App
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: yarn run start:dev
    depends_on:
      - db
    ports:
      - '5000:5000'
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - DB_DAILECT=$DB_DAILECT
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_LOGGING=$DB_LOGGING

  # MySQL Database
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - $HOME/database:/var/lib/mysql
